name: CI

on:
  push:
    branches: [ main ]

jobs:
  CI_CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo Hello World!!

      - name: change scripts permissions
        run: |
          chmod +x ci/setup.sh
          chmod +x ci/setup_env.sh
          chmod +x ci/deploy.sh
          chmod +x ci/build.sh
          chmod +x ci/pipeline.sh
          chmod +x ci/test.sh

      - name: Setup Environment
        run: ./ci/setup_env.sh
        env:
          CA_PEM: ${{ secrets.CA_PEM }}

      - name: run pipeline
        run: |
          ./ci/pipeline.sh