name: CI

on:
  push:
    branches: [ main ]

jobs:
  CI_CD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo Hello World!!

      - name: create local container
        run: docker-compose -f docker-compose.test.yml up -d --build

      - name: change scripts permissions
        run: |
          chmod +x ci/setup.sh
          chmod +x ci/deploy.sh
          chmod +x ci/build.sh
          chmod +x ci/pipeline.sh
          chmod +x ci/test.sh

      - name: run pipeline
        run: |
          ./ci/pipeline.sh